# Generated by Django 2.2.16 on 2020-10-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='ws',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='wsws',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
